Nexsus/Nexsus/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Nexsus.Model.Model;
using Nexsus.Models;
using Nexsus.BLL.Manager;
using Nexsus.DatabaseContext.DatabaseContext;

namespace Nexsus.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryModel _categoryModel = new CategoryModel();
        CategoryManager  _categoryManager = new CategoryManager();
        ProjectDbContext _dbContext = new ProjectDbContext();

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Add()
        {

            CategoryViewModel categoryViewModel = new CategoryViewModel();

            categoryViewModel.Categorys = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        [HttpPost]
        public ActionResult Add(CategoryViewModel categoryViewModel)
        {
           


            string message;
            if (ModelState.IsValid)
            {
                
               
                CategoryModel category = Mapper.Map<CategoryModel>(categoryViewModel);
                if (_categoryManager.IsExist(category))
                {
                    message = "Data is already Exist In Database";
                   
                }
                else
                {
                    if (_categoryManager.Add(category))
                    {

                        message = "Saved";
                    }
                    else
                    {
                        message = "Not Saved";
                    }
                }

              
            }
            else
            {
                message = "ModelState Failed";
            }

            

            //

            //if (DuplicateEntry(categoryViewModel))


            // { 
            //    message ="Code is Exist";
            //    return View();
            // }

            ViewBag.Message = message;
            categoryViewModel.Categorys = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        public ActionResult Edit(int id)
        {
            CategoryModel category = _categoryManager.GetById(id);
            CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(category);
            return View(categoryViewModel);
        }
        [HttpPost]
        public ActionResult Edit(CategoryViewModel categoryViewModel)
        {
            string message;
            if (ModelState.IsValid)
            {

                CategoryModel category = Mapper.Map<CategoryModel>(categoryViewModel);

                //if (_categoryManager.IsExist(category))
                //{
                //    message = "Data is already Exist In Database";

                //}
                //else
               // {
                    if (_categoryManager.Update(category))
                    {

                        message = "Update";
                    }
                    else
                    {
                        message = "Not Update";
                    }
               // }

              
            }
            else
            {
                message = "ModelState Failed";
            }


            //


            ViewBag.Message = message;
            categoryViewModel.Categorys = _categoryManager.GetAll();
            return View(categoryViewModel);
        }
      

        public ActionResult Search(string seacrhing)
        {
           //CategoryViewModel categoryViewModel = new CategoryViewModel();
           //categoryViewModel.Categorys = _categoryManager.GetAll();
           //return View(categoryViewModel);
         
           var category = from s in _dbContext.CategoryDatabaSet select s;
           if (!String.IsNullOrEmpty(seacrhing))
           {
               category = category.Where(s => s.Code.Contains(seacrhing) || s.Name.Contains(seacrhing));
               


           }

          
           return View(category.ToList());

        }

        //[HttpPost]
        //public ActionResult Search(CategoryViewModel categoryViewModel)
        //{
        //    string message;

        //    var categorys = _categoryManager.GetAll();
        //    if (categoryViewModel.Code != null)
        //    {
        //        categorys = categorys.Where(c => c.Code.Contains(categoryViewModel.Code)).ToList();

        //    }


        //    if (categoryViewModel.Name != null)
        //    {
        //        categorys = categorys.Where(c => c.Name.Contains(categoryViewModel.Name)).ToList();
        //    }

        //    categoryViewModel.Categorys = categorys;
        //    return View(categoryViewModel);
        //}

        //public JsonResult CodeUnique(CategoryModel categoryModel)
        //{
        //    return IsExist(categoryModel.Code, categoryModel.Name)
        //        ? Json(true, JsonRequestBehavior.AllowGet)
        //        : Json(false, JsonRequestBehavior.AllowGet);
        //}

        //public bool IsExist(string Code, string Name)
        //{
        //    //True:False--- action that implement to check barcode uniqueness

        //    return false;//Always return false to display error message
        //}
       
        //public ActionResult CheckExist(string code, string name )
        //{
        //    var validateName = _dbContext.CategoryDatabaSet.FirstOrDefault
        //        (x => x.Code == code || x.Name == name);
        //    if (validateName != null)
        //    {
        //        return Json(false, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        return Json(true, JsonRequestBehavior.AllowGet);
        //    }
        //}




    }






    }

Nexsus/Nexsus/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Nexsus.Model.Model;
using Nexsus.Models;
using Nexsus.BLL.Manager;

namespace Nexsus.Controllers
{
    public class SupplierController : Controller
    {
        // GET: Supplier

        SupplierModel  _supplierModel = new SupplierModel();
         SupplierManger _supplierManger = new SupplierManger();


         public ActionResult Add()
         {

             SupplierViewModel supplierViewModel = new SupplierViewModel();

             supplierViewModel.Suppliers = _supplierManger.GetAll();
             return View(supplierViewModel);
         }


         [HttpPost]
         public ActionResult Add(SupplierViewModel supplierViewModel)
         {



             string message;
             if (ModelState.IsValid)
             {


                 SupplierModel supplier = Mapper.Map<SupplierModel>(supplierViewModel);
                
                 
                     if (_supplierManger.Add(supplier))
                     {

                         message = "Saved";
                     }
                     else
                     {
                         message = "Not Saved";
                     }
                 


             }
             else
             {
                 message = "ModelState Failed";
             }



          
             ViewBag.Message = message;
             supplierViewModel.Suppliers = _supplierManger.GetAll();
             return View(supplierViewModel);
         }
    }
}

Nexsus/Nexsus/Views/Shared/_Layout.cshtml
<style>
    .navbar{background:#222222;}
    .nav-item::after{content:'';display:block;width:0px;height:2px;background:#fec400;transition: 0.2s;}
    .nav-item:hover::after{width:100%;}
    .navbar-dark .navbar-nav .active > .nav-link, .navbar-dark .navbar-nav .nav-link.active, .navbar-dark .navbar-nav .nav-link.show, .navbar-dark .navbar-nav .show > .nav-link,.navbar-dark .navbar-nav .nav-link:focus, .navbar-dark .navbar-nav .nav-link:hover{color:#fec400;}
    .nav-link{padding:15px 5px;transition:0.2s;}
    .dropdown-item.active, .dropdown-item:active{color:#212529;}
    .dropdown-item:focus, .dropdown-item:hover{background:#fec400;}

</style>
<!------ Include the above in your HEAD tag ---------->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<nav class="navbar navbar-expand-lg navbar-dark">
    <a href="@Url.Action("Home", "Category")" class="navbar-brand">Small Business Management System</a>
    <button class="navbar-toggler" type="button" data-target="#navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            @*<li class="nav-item active">
                <a href="@Url.Action("Home", "Category")" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Product</a>
            </li>*@
            @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="@Url.Action("Add", "Category")" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Category</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    <a href="@Url.Action("Add", "Category")" class="dropdown-item">Entry Category</a>
                    <a href="@Url.Action("Search", "Category")" class="dropdown-item">Search Category</a>
                   
                </div>
                        
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="@Url.Action("Add", "Category")" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Product</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    <a href="@Url.Action("Add", "Category")" class="dropdown-item">Entry Product</a>
                    <a href="@Url.Action("Search", "Category")" class="dropdown-item">Search Product</a>

                </div>

            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="@Url.Action("Add", "Category")" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Customer</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    <a href="@Url.Action("Add", "Category")" class="dropdown-item">Entry Customer</a>
                    <a href="@Url.Action("Search", "Category")" class="dropdown-item">Search Customer</a>

                </div>

            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="@Url.Action("Add", "Category")" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Supplier</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    <a href="@Url.Action("Add", "Category")" class="dropdown-item">Entry Supplier</a>
                    <a href="@Url.Action("Search", "Category")" class="dropdown-item">Search Supplier</a>

                </div>

            </li>*@
            
            <li class="nav-item">
                <a href="@Url.Action("Add", "Category")" class="nav-link">Category</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Add", "Category")" class="nav-link">Product</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Add", "Category")" class="nav-link">Customer</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Add", "Supplier")" class="nav-link">Supplier</a>
            </li>
        </ul>
    </div>
</nav>

<body>

@RenderBody()
@RenderSection("MyScript", false)
</body>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>